119 mainenance cast
CZ-NIC/django-eidas-specific-node pull request #122
Opened 2023-01-24 09:47 UTC by tdivis

2023-01-30 14:19 UTC, tdivis commented on eidas_node/models.py
> +        data = '|'.join((str(self.id), str(self.issuer), create_eidas_timestamp(cast(datetime, self.created)), secret))
OK, rewrote to `assert XXX is not None` here and in several other instances, so it's consistent.

2023-01-30 14:21 UTC, tdivis commented
I have added test compatibility with libxmlsec>1.2.34, @tpazderka please have a look.

2023-02-01 08:34 UTC, tpazderka requested changes

2023-02-01 08:34 UTC, tpazderka commented on eidas_node/tests/test_xml.py
> +            filename = 'signed_response_and_assertion.xml_1.2.35.xml'
The file seems to be missing.

2023-02-01 08:34 UTC, tpazderka commented on eidas_node/tests/test_xml.py
> +            filename = 'signed_response_1.2.35.xml'
This file seems to be missing.

2023-02-01 08:34 UTC, tpazderka commented on .github/workflows/python-test.yml
> +        python: [3.8, 3.9]
We are claiming support for python 3.5-3.7 as well, but we are not testing it. 
Out of those, 3.7 is still supported version, so we shouldn't drop that one.
I would add another job that runs the older python version(s)...

2023-02-01 11:36 UTC, tpazderka approved these changes

2023-02-01 12:44 UTC, merged